services:
  server:
    build: ./server/.
    env_file:
      - global.env
      - server.env
    ports:
      - "3078:3003"
  frontend:
    build: ./frontend/.
    env_file:
      - global.env
    ports:
      - "3079:80"